import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const stolenFont = localFont({
  src: "../public/ducker-stolen-font.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={stolenFont.className}>{children}</body>
    </html>
  );
}
